/*******************************************************************************
 * Copyright (c) 2016
 * Author: Steve Legge
 * All rights reserved.
 *******************************************************************************/
package org.hamlookup.web.model;
// Generated Sep 10, 2016 7:46:59 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PubaccAmId generated by hbm2java
 */

@Entity
@Table(name = "PUBACC_AM")
public class PubaccAm implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6088283657391822756L;
	
	private String record_type;
	
	@Id
	private int unique_system_identifier;
	private String uls_file_num;
	private String ebf_number;
	private String callsign;
	private String operator_class;
	private String group_code;
	private Byte region_code;
	private String trustee_callsign;
	private String trustee_indicator;
	private String physician_certification;
	private String ve_signature;
	private String systematic_callsign_change;
	private String vanity_callsign_change;
	private String vanity_relationship;
	private String previous_callsign;
	private String previous_operator_class;
	private String trustee_name;

	public PubaccAm() {
	}

	public PubaccAm(String recordType, int uniqueSystemIdentifier) {
		this.record_type = recordType;
		this.unique_system_identifier = uniqueSystemIdentifier;
	}

	public PubaccAm(String recordType, int uniqueSystemIdentifier, String ulsFileNum, String ebfNumber,
			String callsign, String operatorClass, String groupCode, Byte regionCode, String trusteeCallsign,
			String trusteeIndicator, String physicianCertification, String veSignature,
			String systematicCallsignChange, String vanityCallsignChange, String vanityRelationship,
			String previousCallsign, String previousOperatorClass, String trusteeName) {
		this.record_type = recordType;
		this.unique_system_identifier = uniqueSystemIdentifier;
		this.uls_file_num = ulsFileNum;
		this.ebf_number = ebfNumber;
		this.callsign = callsign;
		this.operator_class = operatorClass;
		this.group_code = groupCode;
		this.region_code = regionCode;
		this.trustee_callsign = trusteeCallsign;
		this.trustee_indicator = trusteeIndicator;
		this.physician_certification = physicianCertification;
		this.ve_signature = veSignature;
		this.systematic_callsign_change = systematicCallsignChange;
		this.vanity_callsign_change = vanityCallsignChange;
		this.vanity_relationship = vanityRelationship;
		this.previous_callsign = previousCallsign;
		this.previous_operator_class = previousOperatorClass;
		this.trustee_name = trusteeName;
	}

	public String getRecord_type() {
		return record_type;
	}

	public void setRecord_type(String record_type) {
		this.record_type = record_type;
	}

	public int getUnique_system_identifier() {
		return unique_system_identifier;
	}

	public void setUnique_system_identifier(int unique_system_identifier) {
		this.unique_system_identifier = unique_system_identifier;
	}

	public String getUls_file_num() {
		return uls_file_num;
	}

	public void setUls_file_num(String uls_file_num) {
		this.uls_file_num = uls_file_num;
	}

	public String getEbf_number() {
		return ebf_number;
	}

	public void setEbf_number(String ebf_number) {
		this.ebf_number = ebf_number;
	}

	public String getCallsign() {
		return callsign;
	}

	public void setCallsign(String callsign) {
		this.callsign = callsign;
	}

	public String getOperator_class() {
		return operator_class;
	}

	public void setOperator_class(String operator_class) {
		this.operator_class = operator_class;
	}

	public String getGroup_code() {
		return group_code;
	}

	public void setGroup_code(String group_code) {
		this.group_code = group_code;
	}

	public Byte getRegion_code() {
		return region_code;
	}

	public void setRegion_code(Byte region_code) {
		this.region_code = region_code;
	}

	public String getTrustee_callsign() {
		return trustee_callsign;
	}

	public void setTrustee_callsign(String trustee_callsign) {
		this.trustee_callsign = trustee_callsign;
	}

	public String getTrustee_indicator() {
		return trustee_indicator;
	}

	public void setTrustee_indicator(String trustee_indicator) {
		this.trustee_indicator = trustee_indicator;
	}

	public String getPhysician_certification() {
		return physician_certification;
	}

	public void setPhysician_certification(String physician_certification) {
		this.physician_certification = physician_certification;
	}

	public String getVe_signature() {
		return ve_signature;
	}

	public void setVe_signature(String ve_signature) {
		this.ve_signature = ve_signature;
	}

	public String getSystematic_callsign_change() {
		return systematic_callsign_change;
	}

	public void setSystematic_callsign_change(String systematic_callsign_change) {
		this.systematic_callsign_change = systematic_callsign_change;
	}

	public String getVanity_callsign_change() {
		return vanity_callsign_change;
	}

	public void setVanity_callsign_change(String vanity_callsign_change) {
		this.vanity_callsign_change = vanity_callsign_change;
	}

	public String getVanity_relationship() {
		return vanity_relationship;
	}

	public void setVanity_relationship(String vanity_relationship) {
		this.vanity_relationship = vanity_relationship;
	}

	public String getPrevious_callsign() {
		return previous_callsign;
	}

	public void setPrevious_callsign(String previous_callsign) {
		this.previous_callsign = previous_callsign;
	}

	public String getPrevious_operator_class() {
		return previous_operator_class;
	}

	public void setPrevious_operator_class(String previous_operator_class) {
		this.previous_operator_class = previous_operator_class;
	}

	public String getTrustee_name() {
		return trustee_name;
	}

	public void setTrustee_name(String trustee_name) {
		this.trustee_name = trustee_name;
	}
	
}
