/*******************************************************************************
 * Copyright (c) 2016
 * Author: Steve Legge
 * All rights reserved.
 *******************************************************************************/
package org.hamlookup.web.model;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PubaccCo generated by hbm2java
 */
@Entity
@Table(name = "PUBACC_CO")
public class PubaccCo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5065141800020137986L;
	
	@Id
	private PubaccCoId id;

	public PubaccCoId getId() {
		return this.id;
	}

	public void setId(PubaccCoId id) {
		this.id = id;
	}

}