/*******************************************************************************
 * Copyright (c) 2016
 * Author: Steve Legge
 * All rights reserved.
 *******************************************************************************/
package org.hamlookup.web.model;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PubaccSf generated by hbm2java
 */
@Entity
@Table(name = "PUBACC_SF")
public class PubaccSf implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7397984916775361462L;
	
	@Id
	private int unique_system_identifier;
	private String record_type;
	private String uls_file_number;
	private String ebf_number;
	private String callsign;
	private String lic_freeform_cond_type;
	private Integer unique_lic_freeform_id;
	private Integer sequence_number;
	private String lic_freeform_condition;
	private String status_code;
	private String status_date;

	public PubaccSf() {
	}

	public PubaccSf(int uniqueSystemIdentifier) {
		this.unique_system_identifier = uniqueSystemIdentifier;
	}

	public PubaccSf(int uniqueSystemIdentifier, String recordType, String ulsFileNumber, String ebfNumber,
			String callsign, String licFreeformCondType, Integer uniqueLicFreeformId, Integer sequenceNumber,
			String licFreeformCondition, String statusCode, String statusDate) {
		this.unique_system_identifier = uniqueSystemIdentifier;
		this.record_type = recordType;
		this.uls_file_number = ulsFileNumber;
		this.ebf_number = ebfNumber;
		this.callsign = callsign;
		this.lic_freeform_cond_type = licFreeformCondType;
		this.unique_lic_freeform_id = uniqueLicFreeformId;
		this.sequence_number = sequenceNumber;
		this.lic_freeform_condition = licFreeformCondition;
		this.status_code = statusCode;
		this.status_date = statusDate;
	}

	public int getUnique_system_identifier() {
		return unique_system_identifier;
	}

	public void setUnique_system_identifier(int unique_system_identifier) {
		this.unique_system_identifier = unique_system_identifier;
	}

	public String getRecord_type() {
		return record_type;
	}

	public void setRecord_type(String record_type) {
		this.record_type = record_type;
	}

	public String getUls_file_number() {
		return uls_file_number;
	}

	public void setUls_file_number(String uls_file_number) {
		this.uls_file_number = uls_file_number;
	}

	public String getEbf_number() {
		return ebf_number;
	}

	public void setEbf_number(String ebf_number) {
		this.ebf_number = ebf_number;
	}

	public String getCallsign() {
		return callsign;
	}

	public void setCallsign(String callsign) {
		this.callsign = callsign;
	}

	public String getLic_freeform_cond_type() {
		return lic_freeform_cond_type;
	}

	public void setLic_freeform_cond_type(String lic_freeform_cond_type) {
		this.lic_freeform_cond_type = lic_freeform_cond_type;
	}

	public Integer getUnique_lic_freeform_id() {
		return unique_lic_freeform_id;
	}

	public void setUnique_lic_freeform_id(Integer unique_lic_freeform_id) {
		this.unique_lic_freeform_id = unique_lic_freeform_id;
	}

	public Integer getSequence_number() {
		return sequence_number;
	}

	public void setSequence_number(Integer sequence_number) {
		this.sequence_number = sequence_number;
	}

	public String getLic_freeform_condition() {
		return lic_freeform_condition;
	}

	public void setLic_freeform_condition(String lic_freeform_condition) {
		this.lic_freeform_condition = lic_freeform_condition;
	}

	public String getStatus_code() {
		return status_code;
	}

	public void setStatus_code(String status_code) {
		this.status_code = status_code;
	}

	public String getStatus_date() {
		return status_date;
	}

	public void setStatus_date(String status_date) {
		this.status_date = status_date;
	}


}
