/*******************************************************************************
 * Copyright (c) 2016
 * Author: Steve Legge
 * All rights reserved.
 *******************************************************************************/
package org.hamlookup.web.model;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated Sep 10, 2016 11:53:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * PubaccLa generated by hbm2java
 */
@Entity
@Table(name = "PUBACC_LA")
public class PubaccLa implements java.io.Serializable {	
	/**
	 * 
	 */
	private static final long serialVersionUID = -2003404475047074190L;
	
	@Id
	private PubaccLaId id;

	public PubaccLaId getId() {
		return this.id;
	}

	public void setId(PubaccLaId id) {
		this.id = id;
	}

}
