/*******************************************************************************
 * Copyright (c) 2016
 * Author: Steve Legge
 * All rights reserved.
 *******************************************************************************/
package org.hamlookup.web.model;
// Generated Sep 10, 2016 7:46:59 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PubaccEn generated by hbm2java
 */


@Entity
@Table(name = "PUBACC_EN")
public class PubaccEn implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2451849688594944038L;
	
	@Id
	private int unique_system_identifier;
	
	private String record_type;
	private String uls_file_number;
	private String ebf_number;
	private String call_sign;
	private String entity_type;
	private String licensee_id;
	private String entity_name;
	private String first_name;
	private String mi;
	private String last_name;
	private String suffix;
	private String phone;
	private String fax;
	private String email;
	private String street_address;
	private String city;
	private String state;
	private String zip_code;
	private String po_box;
	private String attention_line;
	private String sgin;
	private String frn;
	private String applicant_type_code;
	private String applicant_type_other;
	private String status_code;
	private Date status_date;

	public PubaccEn() {
	}

	public PubaccEn(int uniqueSystemIdentifier, String recordType) {
		this.unique_system_identifier = uniqueSystemIdentifier;
		this.record_type = recordType;
	}

	public PubaccEn(int uniqueSystemIdentifier, String recordType, String ulsFileNumber, String ebfNumber,
			String callSign, String entityType, String licenseeId, String entityName, String firstName, String mi,
			String lastName, String suffix, String phone, String fax, String email, String streetAddress, String city,
			String state, String zipCode, String poBox, String attentionLine, String sgin, String frn,
			String applicantTypeCode, String applicantTypeOther, String statusCode, Date statusDate) {
		this.unique_system_identifier = uniqueSystemIdentifier;
		this.record_type = recordType;
		this.uls_file_number = ulsFileNumber;
		this.ebf_number = ebfNumber;
		this.call_sign = callSign;
		this.entity_type = entityType;
		this.licensee_id = licenseeId;
		this.entity_name = entityName;
		this.first_name = firstName;
		this.mi = mi;
		this.last_name = lastName;
		this.suffix = suffix;
		this.phone = phone;
		this.fax = fax;
		this.email = email;
		this.street_address = streetAddress;
		this.city = city;
		this.state = state;
		this.zip_code = zipCode;
		this.po_box = poBox;
		this.attention_line = attentionLine;
		this.sgin = sgin;
		this.frn = frn;
		this.applicant_type_code = applicantTypeCode;
		this.applicant_type_other = applicantTypeOther;
		this.status_code = statusCode;
		this.status_date = statusDate;
	}

	public int getUniqueSystemIdentifier() {
		return this.unique_system_identifier;
	}

	public void setUniqueSystemIdentifier(int uniqueSystemIdentifier) {
		this.unique_system_identifier = uniqueSystemIdentifier;
	}

	public int getUnique_system_identifier() {
		return unique_system_identifier;
	}

	public void setUnique_system_identifier(int unique_system_identifier) {
		this.unique_system_identifier = unique_system_identifier;
	}

	public String getRecord_type() {
		return record_type;
	}

	public void setRecord_type(String record_type) {
		this.record_type = record_type;
	}

	public String getUls_file_number() {
		return uls_file_number;
	}

	public void setUls_file_number(String uls_file_number) {
		this.uls_file_number = uls_file_number;
	}

	public String getEbf_number() {
		return ebf_number;
	}

	public void setEbf_number(String ebf_number) {
		this.ebf_number = ebf_number;
	}

	public String getCall_sign() {
		return call_sign;
	}

	public void setCall_sign(String call_sign) {
		this.call_sign = call_sign;
	}

	public String getEntity_type() {
		return entity_type;
	}

	public void setEntity_type(String entity_type) {
		this.entity_type = entity_type;
	}

	public String getLicensee_id() {
		return licensee_id;
	}

	public void setLicensee_id(String licensee_id) {
		this.licensee_id = licensee_id;
	}

	public String getEntity_name() {
		return entity_name;
	}

	public void setEntity_name(String entity_name) {
		this.entity_name = entity_name;
	}

	public String getFirst_name() {
		return first_name;
	}

	public void setFirst_name(String first_name) {
		this.first_name = first_name;
	}

	public String getMi() {
		return mi;
	}

	public void setMi(String mi) {
		this.mi = mi;
	}

	public String getLast_name() {
		return last_name;
	}

	public void setLast_name(String last_name) {
		this.last_name = last_name;
	}

	public String getSuffix() {
		return suffix;
	}

	public void setSuffix(String suffix) {
		this.suffix = suffix;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFax() {
		return fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getStreet_address() {
		return street_address;
	}

	public void setStreet_address(String street_address) {
		this.street_address = street_address;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZip_code() {
		return zip_code;
	}

	public void setZip_code(String zip_code) {
		this.zip_code = zip_code;
	}

	public String getPo_box() {
		return po_box;
	}

	public void setPo_box(String po_box) {
		this.po_box = po_box;
	}

	public String getAttention_line() {
		return attention_line;
	}

	public void setAttention_line(String attention_line) {
		this.attention_line = attention_line;
	}

	public String getSgin() {
		return sgin;
	}

	public void setSgin(String sgin) {
		this.sgin = sgin;
	}

	public String getFrn() {
		return frn;
	}

	public void setFrn(String frn) {
		this.frn = frn;
	}

	public String getApplicant_type_code() {
		return applicant_type_code;
	}

	public void setApplicant_type_code(String applicant_type_code) {
		this.applicant_type_code = applicant_type_code;
	}

	public String getApplicant_type_other() {
		return applicant_type_other;
	}

	public void setApplicant_type_other(String applicant_type_other) {
		this.applicant_type_other = applicant_type_other;
	}

	public String getStatus_code() {
		return status_code;
	}

	public void setStatus_code(String status_code) {
		this.status_code = status_code;
	}

	public Date getStatus_date() {
		return status_date;
	}

	public void setStatus_date(Date status_date) {
		this.status_date = status_date;
	}

}
