/*******************************************************************************
 * Copyright (c) 2016
 * Author: Steve Legge
 * All rights reserved.
 *******************************************************************************/
package org.hamlookup.web.model;

import javax.persistence.Embeddable;

/**
 * PubaccCoId generated by hbm2java
 */
@Embeddable
public class PubaccCoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8366105424819834922L;
	
	private String record_type;
	private int unique_system_identifier;
	private String uls_file_num;
	private String callsign;
	private String comment_date;
	private String description;
	private String status_code;

	public PubaccCoId() {
	}

	public PubaccCoId(String recordType, int uniqueSystemIdentifier) {
		this.record_type = recordType;
		this.unique_system_identifier = uniqueSystemIdentifier;
	}

	public PubaccCoId(String recordType, int uniqueSystemIdentifier, String ulsFileNum, String callsign,
			String commentString, String description, String statusCode) {
		this.record_type = recordType;
		this.unique_system_identifier = uniqueSystemIdentifier;
		this.uls_file_num = ulsFileNum;
		this.callsign = callsign;
		this.comment_date = commentString;
		this.description = description;
		this.status_code = statusCode;
	}

	public String getRecord_type() {
		return record_type;
	}

	public void setRecord_type(String record_type) {
		this.record_type = record_type;
	}

	public int getUnique_system_identifier() {
		return unique_system_identifier;
	}

	public void setUnique_system_identifier(int unique_system_identifier) {
		this.unique_system_identifier = unique_system_identifier;
	}

	public String getUls_file_num() {
		return uls_file_num;
	}

	public void setUls_file_num(String uls_file_num) {
		this.uls_file_num = uls_file_num;
	}

	public String getCallsign() {
		return callsign;
	}

	public void setCallsign(String callsign) {
		this.callsign = callsign;
	}

	public String getComment_date() {
		return comment_date;
	}

	public void setComment_date(String comment_date) {
		this.comment_date = comment_date;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getStatus_code() {
		return status_code;
	}

	public void setStatus_code(String status_code) {
		this.status_code = status_code;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PubaccCoId))
			return false;
		PubaccCoId castOther = (PubaccCoId) other;

		return ((this.getRecord_type() == castOther.getRecord_type()) || (this.getRecord_type() != null
				&& castOther.getRecord_type() != null && this.getRecord_type().equals(castOther.getRecord_type())))
				&& (this.getUnique_system_identifier() == castOther.getUnique_system_identifier())
				&& ((this.getUls_file_num() == castOther.getUls_file_num()) || (this.getUls_file_num() != null
						&& castOther.getUls_file_num() != null && this.getUls_file_num().equals(castOther.getUls_file_num())))
				&& ((this.getCallsign() == castOther.getCallsign()) || (this.getCallsign() != null
						&& castOther.getCallsign() != null && this.getCallsign().equals(castOther.getCallsign())))
				&& ((this.getComment_date() == castOther.getComment_date())
						|| (this.getComment_date() != null && castOther.getComment_date() != null
								&& this.getComment_date().equals(castOther.getComment_date())))
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())))
				&& ((this.getStatus_code() == castOther.getStatus_code()) || (this.getStatus_code() != null
						&& castOther.getStatus_code() != null && this.getStatus_code().equals(castOther.getStatus_code())));		
	
	}

	public int hashCode() {
		int result = 16;

		result = 37 * result + (getRecord_type() == null ? 0 : this.getRecord_type().hashCode());
		result = 37 * result + this.getUnique_system_identifier();
		result = 37 * result + (getUls_file_num() == null ? 0 : this.getUls_file_num().hashCode());
		result = 37 * result + (getCallsign() == null ? 0 : this.getCallsign().hashCode());
		result = 37 * result + (getComment_date() == null ? 0 : this.getComment_date().hashCode());
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		result = 37 * result + (getStatus_code() == null ? 0 : this.getStatus_code().hashCode());
		return result;
	}

}
